version: '3'

services:
  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    hostname: graphite
    volumes:
      - graphite-storage:/opt/graphite/storage
    ports:
      - 8080:80
      - 2003-2004:2003-2004
      - 2023-2024:2023-2024
      - 8125:8125/udp
      - 8126:8126
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
      - GF_INSTALL_PLUGINS=jdbranham-diagram-panel
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - graphite
volumes:
  graphite-storage:
  grafana-storage:
